# Generated by Django 4.1.1 on 2022-09-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mouseheatmapapp", "0002_heatmapinfo"),
    ]

    operations = [
        migrations.RenameModel(old_name="HeatmapInfo", new_name="InitialData",),
    ]
