# Generated by Django 4.1.1 on 2022-10-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouseheatmapapp", "0003_rename_heatmapinfo_initialdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="initialdata",
            name="pub_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
