# Generated by Django 4.1.1 on 2022-10-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mouseheatmapapp",
            "0005_initialdata_folder_path_initialdata_max_mouse_click_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="initialdata",
            name="folder_path",
            field=models.FilePathField(max_length=255),
        ),
    ]
