# Generated by Django 4.1.1 on 2022-10-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mouseheatmapapp", "0006_alter_initialdata_folder_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initialdata",
            name="folder_path",
            field=models.CharField(default="", max_length=255),
        ),
    ]
